version: '3'
services: 
  # keycloak:
  #   image: 'quay.io/keycloak/keycloak:12.0.2'
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=andi
  #     # - PROXY_ADDRESS_FORWARDING=true
  #     # - KEYCLOAK_LOGLEVEL=DEBUG
  #     # - ROOT_LOGLEVEL=DEBUG
  #     # - DEBUG=true
  #   ports: 
  #     - '8080:8080'
      # - '127.0.0.1:8080:8080'
      # - '172.17.208.1:8080:8080'
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
      # volumes: 
      #   - /app/target
      #   - ./:/app
    ports:
      - '8090:8090'

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    # volumes: 
    #   - /app/node_modules
    #   - ./:/app
    environment: 
      - PORT=3000
      # - AUTH_SERVER_URL=http://keycloak:8080/auth/
      - AUTH_SERVER_URL=http://192.168.1.11:8080/auth/
      #using the localhost for keycloak does NOT work - Access denied
      #using the external IP for keycloak is working fine
      # - AUTH_SERVER_URL=http://172.17.208.1:8080/auth/
      # - AUTH_SERVER_URL=http://localhost:8080/auth/
      - BACKEND_URL=http://192.168.1.11:8090/courses
      # - BACKEND_URL=http://172.23.192.1:8090/courses   
    ports: 
      - '3000:3000'
    depends_on: 
      - backend

