apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-keycloak-java-frontend-deployment
spec:
  selector:
    matchLabels:
      app: edge-keycloak-java-frontend
  template:
    metadata:
      labels:
        app: edge-keycloak-java-frontend
    spec:
      containers:
      - name: edge-keycloak-java-frontend
        image: edge-keycloak-java-frontend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
